// Editorial summaries, checked 2026-09-30. Examples and quizzes are original teaching scenarios.
export const learningContent = {
  health: {
    readTime: '3 menit',
    steps: ['Citra medis menjadi masukan bagi model yang telah dilatih mengenali pola.', 'Model menghasilkan prediksi atau penanda area yang perlu ditinjau.', 'Tenaga medis menilai hasil bersama informasi klinis pasien.'],
    stepSource: 0,
    evidence: { text: 'Tinjauan sistematis Aggarwal dan rekan (2021) mencakup 503 studi pencitraan medis. Hasil deep learning menjanjikan, tetapi metode dan hasil antarpenelitian sangat beragam; akurasi dapat tampak terlalu tinggi jika evaluasinya lemah.', source: 0 },
    limitation: 'Kinerja pada data latihan tidak membuktikan kinerja di rumah sakit lain. Validasi eksternal memakai data baru yang mewakili pasien sasaran sangat penting. Studi ini menelusuri literatur hingga Januari 2020, bukan seluruh sistem AI terbaru.',
    limitationSource: 0,
    example: 'Sebuah sistem menandai area pada X-Ray untuk ditinjau. Dokter membandingkannya dengan gejala dan pemeriksaan lain. Penanda AI adalah masukan untuk evaluasi, bukan keputusan akhir.',
    action: 'Tanyakan tujuan penggunaan data, siapa yang dapat mengaksesnya, dan bagaimana keputusan dapat ditinjau manusia. WHO menempatkan otonomi manusia, kerahasiaan, keselamatan, serta kesetaraan sebagai prinsip utama.',
    actionSource: 1,
    quiz: { question: 'AI berhasil pada data rumah sakit A. Apa yang perlu dilakukan sebelum digunakan di rumah sakit B?', options: ['Langsung gunakan karena akurasinya tinggi.', 'Uji dengan data baru yang mewakili pasien B.', 'Hilangkan peninjauan dokter agar lebih cepat.'], correct: 1, explanation: 'Validasi eksternal membantu mengetahui apakah model bekerja pada populasi dan kondisi yang berbeda. Nilai akurasi pada satu kumpulan data belum cukup.' },
    sources: [
      { title: 'Diagnostic accuracy of deep learning in medical imaging: a systematic review and meta-analysis', publisher: 'Aggarwal et al. · npj Digital Medicine', year: '2021', type: 'Jurnal • tinjauan sistematis', url: 'https://www.nature.com/articles/s41746-021-00438-z' },
      { title: 'Ethics and governance of artificial intelligence for health', publisher: 'WHO', year: '2021', type: 'Panduan lembaga kesehatan', url: 'https://www.who.int/news/item/28-06-2021-who-issues-first-global-report-on-ai-in-health-and-six-guiding-principles-for-its-design-and-use' },
    ],
  },
  transport: {
    readTime: '3 menit',
    steps: ['Sensor membantu mendeteksi objek dan kondisi di sekitar kendaraan.', 'Sistem menilai situasi dan merencanakan respons dalam batas operasinya.', 'Jika kondisi melampaui kemampuan sistem, diperlukan respons untuk mengurangi risiko.'],
    stepSource: 0,
    evidence: { text: 'Panduan NHTSA menjelaskan Operational Design Domain (ODD): kondisi tempat sistem otomatis dirancang bekerja, misalnya jenis jalan, rentang kecepatan, wilayah, dan cuaca. Klaim kemampuan perlu dibaca bersama batas ini.', source: 0 },
    limitation: 'Bantuan pengemudi tidak sama dengan kendaraan yang sepenuhnya mandiri. Pada otomasi Level 2, pengemudi tetap harus mengawasi dan bertanggung jawab atas tugas mengemudi.',
    limitationSource: 1,
    example: 'Bus kampus dirancang untuk rute tertentu. Saat hujan mengurangi kemampuan sensor di luar batas operasinya, sistem mengikuti prosedur pengurangan risiko, misalnya menuju penghentian yang aman.',
    action: 'Periksa kondisi penggunaan yang diizinkan dan prosedur ketika sistem gagal. Dalam panduan ini, manfaat keselamatan adalah tujuan yang harus dibuktikan melalui pengujian, bukan jaminan untuk setiap perjalanan.',
    actionSource: 0,
    quiz: { question: 'Fitur Level 2 mengendalikan setir dan kecepatan. Bolehkah pengemudi berhenti mengawasi?', options: ['Boleh, karena dua tugas sudah otomatis.', 'Boleh selama jalan lurus.', 'Tidak, pengemudi tetap harus mengawasi.'], correct: 2, explanation: 'NHTSA membedakan bantuan pengemudi Level 2 dari otomasi yang mengambil alih tugas mengemudi dalam kondisi tertentu. Nama fitur tidak menghapus kewajiban pengawasan.' },
    sources: [
      { title: 'Automated Driving Systems 2.0: A Vision for Safety', publisher: 'NHTSA · U.S. Department of Transportation', year: '2017', type: 'Panduan teknis sukarela • bukan aturan Indonesia', url: 'https://www.nhtsa.gov/sites/nhtsa.dot.gov/files/documents/13069a-ads2.0_090617_v9a_tag.pdf' },
      { title: 'Driver Assistance Technologies', publisher: 'NHTSA', year: 'Halaman edukasi', type: 'Sumber resmi • tingkat otomasi', url: 'https://www.nhtsa.gov/vehicle-safety/driver-assistance-technologies' },
    ],
  },
  industry: {
    readTime: '3 menit',
    steps: ['Pengendali menjalankan gerakan lengan dan alat penjepit untuk tugas tertentu.', 'Sensor dan fungsi keselamatan membantu mengawasi interaksi dengan pekerja.', 'Manusia menyiapkan, memeriksa, dan merawat sistem sesuai penilaian risikonya.'],
    stepSource: 0,
    evidence: { text: 'OSHA menjelaskan bahwa aplikasi robot kolaboratif dirancang untuk berinteraksi langsung dengan pekerja. Keselamatan tetap harus dinilai untuk seluruh aplikasi, termasuk gripper, benda kerja, dan kemungkinan benturan atau terjepit.', source: 0 },
    limitation: 'Label “kolaboratif” tidak otomatis menjadikan semua tugas aman. Fungsi pembatasan gaya atau kecepatan, penghentian protektif, serta pelatihan perlu dipilih berdasarkan risiko. Gerakan robot yang terprogram juga tidak dengan sendirinya membuktikan adanya AI.',
    limitationSource: 0,
    example: 'Robot memindahkan kotak, sementara pekerja memeriksa kemasannya. Jika tugas berubah menjadi menangani benda tajam, penilaian risiko perlu ditinjau lagi meskipun lengannya sama.',
    action: 'Diskusikan pembagian tugas dan pelatihan ulang. Analisis ILO (2025) tentang AI generatif mengukur potensi paparan tugas, bukan jumlah PHK yang pasti terjadi. Temuannya tidak boleh langsung dianggap ukuran dampak robot industri.',
    actionSource: 1,
    quiz: { question: 'Gripper robot diganti untuk membawa benda tajam. Apa langkah yang masuk akal?', options: ['Tinjau ulang risiko seluruh aplikasi.', 'Anggap aman karena robot berlabel kolaboratif.', 'Cukup mengganti warna lampu status.'], correct: 0, explanation: 'Risiko berasal dari keseluruhan tugas: robot, alat, benda kerja, dan manusia. Perubahan alat atau tugas dapat mengubah perlindungan yang dibutuhkan.' },
    sources: [
      { title: 'Industrial Robot Systems and Industrial Robot System Safety', publisher: 'OSHA Technical Manual · Section IV, Chapter 4', year: 'Halaman teknis', type: 'Panduan keselamatan kerja AS', url: 'https://www.osha.gov/otm/section-4-safety-hazards/chapter-4' },
      { title: 'How might generative AI impact different occupations?', publisher: 'International Labour Organization', year: '2025', type: 'Analisis ketenagakerjaan • AI generatif', url: 'https://www.ilo.org/resource/article/how-might-generative-ai-impact-different-occupations' },
    ],
  },
  education: {
    readTime: '3 menit',
    steps: ['Siswa dan guru menentukan tujuan belajar serta konteks pertanyaan.', 'Tutor AI menghasilkan penjelasan atau latihan sebagai bahan belajar.', 'Siswa memeriksa jawaban dan mendiskusikan bagian yang belum dipahami dengan guru.'],
    stepSource: 0,
    evidence: { text: 'UNESCO mendorong penggunaan AI generatif yang berpusat pada manusia. Lembaga pendidikan perlu menilai kesesuaian pedagogis dan etisnya, melindungi data, serta menjaga kendali manusia, inklusi, dan keberagaman.', source: 0 },
    limitation: 'Panduan ini bukan eksperimen yang membuktikan semua tutor AI meningkatkan nilai. Penjelasan yang terdengar meyakinkan tetap perlu diperiksa. Hologram di kota ini adalah ilustrasi pembelajaran, bukan produk yang diuji UNESCO.',
    limitationSource: 0,
    example: 'Untuk belajar pecahan, siswa meminta petunjuk bertahap, mencoba sendiri, lalu membandingkan alasan jawabannya dengan buku dan guru. Ia tidak sekadar menyalin hasil akhir.',
    action: 'Gunakan AI untuk membantu proses berpikir. Jangan masukkan data pribadi yang tidak diperlukan, periksa rujukan, dan jelaskan bagian tugas yang dibantu AI.',
    actionSource: 0,
    quiz: { question: 'Tutor AI memberikan jawaban dan rujukan yang belum pernah kamu lihat. Apa langkah terbaik?', options: ['Salin karena penjelasannya terdengar yakin.', 'Buka sumber aslinya dan periksa bersama materi belajar.', 'Anggap semua jawaban AI selalu salah.'], correct: 1, explanation: 'Verifikasi membantu membedakan jawaban yang didukung bukti dari keluaran yang keliru. Tetap jelaskan dengan kata-katamu sendiri dan minta bantuan guru bila perlu.' },
    sources: [
      { title: 'Guidance for generative AI in education and research', publisher: 'Miao & Holmes · UNESCO', year: '2023', type: 'Panduan pendidikan • halaman diperbarui 2026', url: 'https://www.unesco.org/en/articles/guidance-generative-ai-education-and-research' },
    ],
  },
};
