// Original teaching scenarios derived from each zone's linked readings.
// Each source index points to learning.sources; these are not clinical/safety instructions.
export const extraQuestions = {
  health: [
    { question: 'AI menandai area pada X-Ray. Bagaimana hasil itu digunakan?', options: ['Sebagai masukan yang ditinjau bersama informasi klinis.', 'Sebagai diagnosis akhir tanpa pemeriksaan lain.', 'Sebagai pengganti seluruh tenaga medis.'], correct: 0, explanation: 'Penanda menunjukkan pola yang perlu diperiksa. Penilaian manusia dan konteks pasien tetap diperlukan.', source: 0 },
    { question: 'Tim ingin memakai citra pasien untuk pengembangan AI. Prinsip apa yang perlu didahulukan?', options: ['Mengunggah semuanya agar model cepat belajar.', 'Melindungi kerahasiaan dan memastikan penggunaan data memiliki dasar yang sesuai.', 'Menghapus nama lalu menganggap semua risiko hilang.'], correct: 1, explanation: 'WHO menekankan privasi, kerahasiaan, dan persetujuan yang sah dalam kerangka perlindungan data. Menghapus nama saja bukan alasan untuk mengabaikan tata kelola.', source: 1 },
    { question: 'Data latihan hanya mewakili sebagian kecil kelompok pasien. Apa kekhawatiran utamanya?', options: ['Warna tampilan model menjadi kurang menarik.', 'Semua pasien pasti mendapat hasil salah.', 'Kinerja belum tentu setara pada kelompok yang kurang terwakili.'], correct: 2, explanation: 'Hasil perlu diuji pada populasi sasaran. Kekurangan representasi adalah alasan untuk mengevaluasi, bukan menyimpulkan setiap hasil pasti salah.', source: 1 },
    { question: 'Mengapa satu angka akurasi tinggi belum cukup untuk membandingkan dua sistem?', options: ['Populasi, tugas, dan metode pengujiannya bisa berbeda.', 'Angka tidak pernah berguna dalam penelitian.', 'Sistem dengan nama lebih baru selalu lebih baik.'], correct: 0, explanation: 'Tinjauan pencitraan medis menemukan variasi besar antarmetode penelitian. Perbandingan perlu memperhatikan konteks evaluasi.', source: 0 },
    { question: 'Pasien mempertanyakan hasil yang dibantu AI. Apa bentuk tanggung jawab yang baik?', options: ['Menolak pertanyaan karena algoritma bersifat rahasia.', 'Menyediakan penjelasan dan jalur peninjauan manusia.', 'Meminta pasien menerima hasil tanpa diskusi.'], correct: 1, explanation: 'Transparansi dan akuntabilitas mencakup kesempatan untuk mempertanyakan keputusan dan memperoleh peninjauan yang sesuai.', source: 1 },
    { question: 'Studi yang menelusuri publikasi hingga Januari 2020 dapat digunakan untuk apa?', options: ['Menjamin kemampuan semua produk AI tahun ini.', 'Membuktikan dokter tidak diperlukan lagi.', 'Memahami bukti pada cakupan tersebut sambil mencari evaluasi yang relevan untuk sistem baru.'], correct: 2, explanation: 'Tanggal, populasi, dan lingkup penelitian membatasi kesimpulan. Bukti lama tidak otomatis memvalidasi produk baru.', source: 0 },
  ],
  transport: [
    { question: 'Apa yang termasuk Operational Design Domain (ODD)?', options: ['Warna dan merek bus.', 'Jenis jalan, rentang kecepatan, wilayah, dan kondisi cuaca.', 'Hanya jumlah penumpang.'], correct: 1, explanation: 'ODD menjelaskan batas kondisi operasi sistem, sehingga kemampuan kendaraan harus dinilai dalam batas tersebut.', source: 0 },
    { question: 'Hujan membuat kondisi berada di luar batas operasi bus. Apa tujuan respons sistem?', options: ['Tetap melaju agar jadwal tidak berubah.', 'Mengabaikan sensor yang tidak yakin.', 'Mengurangi risiko melalui prosedur yang telah dirancang dan diuji.'], correct: 2, explanation: 'NHTSA membahas transisi ke kondisi dengan risiko minimal saat batas operasi tidak lagi terpenuhi. Responsnya bergantung pada rancangan sistem.', source: 0 },
    { question: 'Sensor mendeteksi pesepeda di dekat jalur bus. Apa yang masih diperlukan?', options: ['Menilai situasi dan merespons dengan tepat.', 'Cukup menggambar kotak pada layar.', 'Menganggap pesepeda pasti berhenti.'], correct: 0, explanation: 'Deteksi objek perlu diikuti penilaian peristiwa dan respons. Mengenali objek saja belum menyelesaikan tugas mengemudi.', source: 0 },
    { question: 'Sebuah fitur bernama “pintar” dipromosikan pada kendaraan. Bagaimana menilai kemampuannya?', options: ['Percaya nama promosinya saja.', 'Baca batas fungsi dan tanggung jawab pengguna.', 'Anggap semua fitur pintar adalah otomasi penuh.'], correct: 1, explanation: 'Nama pemasaran bukan pengganti informasi tingkat otomasi, batas operasi, dan kewajiban pengawasan.', source: 1 },
    { question: 'Apa bukti yang lebih berguna untuk menilai klaim keselamatan?', options: ['Video demonstrasi singkat di satu jalan.', 'Banyaknya animasi pada dashboard.', 'Pengujian terdokumentasi yang mencakup kondisi operasi dan skenario kegagalan.'], correct: 2, explanation: 'Panduan menekankan pengujian, validasi, serta penelusuran keputusan desain dan risiko. Demo tunggal tidak mencakup semua keadaan.', source: 0 },
    { question: 'Bus berhasil di rute kampus tertutup. Apakah itu membuktikan keberhasilan di semua jalan kota?', options: ['Belum; kondisi dan kompleksitas rute bisa berbeda.', 'Ya, karena busnya sama.', 'Ya, asal warna marka sama.'], correct: 0, explanation: 'Keberhasilan di satu domain operasi tidak otomatis berlaku di domain lain. Perlu evaluasi untuk kondisi penggunaan yang baru.', source: 0 },
  ],
  industry: [
    { question: 'Apa arti “kolaboratif” pada aplikasi robot?', options: ['Robot dirancang berinteraksi langsung dengan pekerja.', 'Robot tidak mungkin melukai siapa pun.', 'Robot selalu menggunakan AI generatif.'], correct: 0, explanation: 'Kolaboratif menjelaskan jenis interaksi. Keselamatan tetap memerlukan penilaian terhadap aplikasi dan tugasnya.', source: 0 },
    { question: 'Bagian mana yang perlu masuk penilaian risiko?', options: ['Hanya merek lengan robot.', 'Robot, alat penjepit, benda kerja, tugas, dan interaksi manusia.', 'Hanya warna lampu status.'], correct: 1, explanation: 'Bahaya dapat muncul dari kombinasi alat, benda yang dibawa, gerakan, dan manusia di ruang kerja.', source: 0 },
    { question: 'Robot mengulangi gerakan yang telah diprogram. Apa kesimpulan yang paling tepat?', options: ['Robot pasti berpikir seperti manusia.', 'Robot pasti memakai model bahasa.', 'Gerakan terprogram saja tidak membuktikan penggunaan AI.'], correct: 2, explanation: 'Otomasi gerak dan AI bukan istilah yang selalu dapat dipertukarkan. Perlu diketahui sistem yang benar-benar digunakan.', source: 0 },
    { question: 'Pemilihan batas gaya dan kecepatan sebaiknya didasarkan pada apa?', options: ['Penilaian risiko dan kebutuhan fungsi keselamatan aplikasi.', 'Keinginan agar robot terlihat cepat.', 'Jumlah pengunjung demonstrasi.'], correct: 0, explanation: 'Fungsi keselamatan dipilih menurut potensi kontak dan risiko tugas. Tidak ada satu pengaturan yang otomatis cocok untuk semua aplikasi.', source: 0 },
    { question: 'ILO menyebut potensi paparan pekerjaan terhadap AI generatif. Apakah ini jumlah PHK yang pasti terjadi?', options: ['Ya, seluruh pekerjaan terpapar pasti hilang.', 'Tidak; paparan adalah potensi perubahan tugas, bukan hasil ketenagakerjaan yang pasti.', 'Ya, dan angkanya juga pasti berlaku pada semua robot.'], correct: 1, explanation: 'Kajian ILO membedakan potensi paparan dari dampak aktual. AI generatif juga tidak identik dengan robot industri.', source: 1 },
    { question: 'Saat pembagian tugas manusia dan mesin berubah, pendekatan mana yang lebih bertanggung jawab?', options: ['Tidak perlu memberi tahu pekerja.', 'Mengabaikan keterampilan baru yang dibutuhkan.', 'Melibatkan pekerja dalam dialog dan menyiapkan pelatihan.'], correct: 2, explanation: 'Transisi kerja perlu mempertimbangkan kemampuan manusia dan dialog sosial, bukan hanya kemampuan teknologinya.', source: 1 },
  ],
  education: [
    { question: 'Bagaimana menggunakan tutor AI untuk memahami pecahan?', options: ['Salin jawaban akhir tanpa mencoba.', 'Minta petunjuk, coba sendiri, lalu periksa alasan jawabannya.', 'Lewati seluruh materi guru.'], correct: 1, explanation: 'AI dapat membantu proses belajar ketika siswa tetap berlatih, memeriksa, dan menjelaskan penalarannya sendiri.', source: 0 },
    { question: 'Chatbot meminta data pribadi yang tidak diperlukan untuk latihan. Apa pilihan yang tepat?', options: ['Berikan semua informasi agar jawabannya lebih panjang.', 'Bagikan juga data teman sekelas.', 'Batasi informasi dan minta bantuan guru bila tidak yakin.'], correct: 2, explanation: 'Perlindungan data merupakan bagian penting penggunaan AI dalam pendidikan. Jangan menambah data pribadi tanpa kebutuhan yang jelas.', source: 0 },
    { question: 'Apa peran guru ketika siswa memakai AI?', options: ['Membimbing tujuan belajar, diskusi, dan penilaian pemahaman.', 'Hanya menyalakan perangkat.', 'Tidak lagi diperlukan.'], correct: 0, explanation: 'Pendekatan berpusat pada manusia mempertahankan peran pendidik dan siswa dalam proses pembelajaran.', source: 0 },
    { question: 'AI membantu membuat kerangka tugas. Bagaimana menjelaskan penggunaannya?', options: ['Mengaku semua dibuat tanpa bantuan.', 'Jelaskan bagian yang dibantu AI dan tetap periksa isi serta sumber.', 'Cukup menulis “dari internet”.'], correct: 1, explanation: 'Transparansi membantu orang memahami proses pengerjaan. Bantuan AI tidak menghapus tanggung jawab atas isi tugas.', source: 0 },
    { question: 'Sebagian siswa tidak memiliki perangkat atau internet. Apa yang perlu dipertimbangkan?', options: ['Siswa tersebut tidak perlu ikut pelajaran.', 'Semua kegiatan wajib memakai chatbot.', 'Sediakan pilihan belajar lain agar akses tetap adil.'], correct: 2, explanation: 'Inklusi berarti manfaat pembelajaran tidak hanya tersedia bagi siswa yang memiliki akses teknologi.', source: 0 },
    { question: 'Apakah panduan UNESCO membuktikan setiap tutor AI pasti menaikkan nilai?', options: ['Tidak; panduan berbeda dari eksperimen yang menguji hasil belajar.', 'Ya, untuk semua mata pelajaran.', 'Ya, tanpa memperhatikan cara penggunaannya.'], correct: 0, explanation: 'Jenis sumber menentukan jenis kesimpulan. Kesesuaian pedagogis dan hasil belajar tetap perlu dievaluasi.', source: 0 },
  ],
};

export const applications = {
  health: [
    ['health-scan', 'Membaca pola citra', 'AI menandai pola pada citra untuk ditinjau tenaga medis; penanda bukan diagnosis akhir.', 'Ilustrasi monitor X-Ray dengan penanda analisis dan scanner medis.', 0],
    ['health-review', 'Dokter tetap meninjau', 'Hasil model dibandingkan dengan konteks pasien dan pemeriksaan lain.', 'Ilustrasi dokter dan pasien membahas citra pada layar.', 0],
    ['health-privacy', 'Melindungi data pasien', 'Akses, tujuan penggunaan, dan kerahasiaan data perlu dikelola.', 'Ilustrasi berkas pasien di balik perisai dan kunci.', 1],
  ],
  transport: [
    ['transport-sensor', 'Mengenali pengguna jalan', 'Sensor mendukung deteksi objek dan respons terhadap situasi lalu lintas.', 'Ilustrasi bus dengan area sensor dan pejalan kaki di persimpangan.', 0],
    ['transport-route', 'Beroperasi dalam batas', 'Rute dan kondisi jalan merupakan bagian dari domain operasi kendaraan.', 'Ilustrasi peta rute bus di dalam batas wilayah operasi.', 0],
    ['transport-weather', 'Menghadapi cuaca berubah', 'Kondisi di luar batas kemampuan memerlukan prosedur pengurangan risiko.', 'Ilustrasi bus, hujan, dan tanda batas kondisi operasi.', 0],
  ],
  industry: [
    ['industry-sort', 'Memindahkan benda', 'Lengan terprogram membantu menangani pekerjaan berulang dalam ruang kerja yang dinilai risikonya.', 'Ilustrasi lengan robot menata kotak pada konveyor.', 0],
    ['industry-safety', 'Berbagi ruang dengan aman', 'Fungsi pembatasan dan penghentian dipilih sesuai potensi bahaya pada tugas.', 'Ilustrasi pekerja dan robot dengan garis batas ruang kerja.', 0],
    ['industry-training', 'Belajar keterampilan baru', 'Perubahan tugas perlu diikuti dialog dan pengembangan keterampilan pekerja.', 'Ilustrasi pelatihan pekerja di depan diagram manusia dan mesin.', 1],
  ],
  education: [
    ['education-tutor', 'Latihan dengan petunjuk', 'Siswa meminta bantuan bertahap, lalu menyelesaikan dan memeriksa soal sendiri.', 'Ilustrasi siswa dan komputer dengan kartu latihan pecahan.', 0],
    ['education-access', 'Memberi pilihan belajar', 'Materi dapat disajikan dalam beragam bentuk; kebutuhan dan akses siswa tetap diperhatikan.', 'Ilustrasi materi belajar berupa teks, audio, dan buku.', 0],
    ['education-discuss', 'Berdiskusi dan memeriksa', 'Siswa membandingkan jawaban AI dengan sumber dan mendiskusikannya bersama guru.', 'Ilustrasi guru dan dua siswa membahas buku serta jawaban AI.', 0],
  ],
};
